name: partaiperindo_webdev1
description: An app built using Flutter for web

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any
  http: any
  html: any
  meta: ^1.1.7
  path: ^1.6.2
  synchronized: ^2.1.0+1

  #flutter_html_view: ^0.5.11
  #cached_network_image: ^0.8.0
  #url_launcher: any
  #webview_flutter: any -> kudu neangan sorangan ku dikustom
  #flutter_widget_from_html_core: ^0.2.1+1

dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0
  pedantic: ^1.0.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui