String StringFontFamily = "Cantarell"; //"Titillium Web"; // "fonts/Cantarell-Regular.ttf"

String StringLabel001 = "Pidato\nKetua Umum";
String StringLabel002 = "Harus ada program pro rakyat,\nperlakuan khusus agar masyarakat\nbawah lebih cepat naik kelas.";
String StringLabel003 = "Hary Tanoesoedibjo";
String StringLabel004 = "Ketua Umum Partai Perindo";
String StringLabel005 = "Trending Stories";
String StringLabel006 = "Liga Futsal Indonesia Sangat Membantu Talenta Muda Indonesia";
String StringLabel007 = "Ahmad Fadhli";
String StringLabel008 = "MNC TV sebagai pemegang hak siar agenda futsal Federasi Futsal Indonesia bakal kembali menyiarkan langsung Pro Futsal League di musim baru ini.";
String StringLabel009 = "Testimoni Mereka";
String StringLabel010 = "Ayu Ting Ting";
String StringLabel011 = "Artis";
String StringLabel012 = "Jangan pernah lelah dan tidak boleh menyerah. Terus jaga niat baik dengan cara-cara baik, optimis dan menggembirakan. Kalau konsisten pasti getarannya akan dirasakan masyarakat. Nyambung dengan rakyat.";
String StringLabel013 = "IT Developer";
String StringLabel014 = "Nadia S."; // Nadia Zerlinda
String StringLabel015 = "Make Up Artist";
String StringLabel016 = "Tinggalkan pikiran yang membuatmu lemah, dan peganglah pikiran yang memberi kekuatan bagimu.";
String StringLabel017 = "Cara terbaik dan mudah untuk membuat orang mengingat adalah dengan keberhasilanmu.";
String StringLabel018 = "Kepuasan terletak pada usaha, bukan pada hasil. Berusaha dengan keras adalah kemenangan yang hakiki.";
String StringLabel019 = "Facebook";
String StringLabel020 = "Twitter";
String StringLabel021 = "Instagram";
String StringLabel022 = "Social Media";
String StringLabel023 = "Redaksi Partai Perindo";
String StringLabel024 = "Berita";
String StringLabel025 = "Terbaru Dari Perindo";
String StringLabel026 = "Kembali Ke Atas";
String StringLabel027 = "\u00a9 2019 Partai Persatuan Indonesia. All right reserved.";
String StringLabel028 = "Chat Online";
String StringLabel029 = "Sekretariat DPP Partai Perindo";
String StringLabel030 = "Jln. Pangeran Diponegoro No.29 - Menteng, Jakarta Pusat 10310";
String StringLabel031 = "Telp. 021-31924109  -  Fax. 021-31925485";
String StringLabel032 = "Email : sekretariat@partaiperindo.com";
String StringLabel033 = "All right reserved \u00a9 2019";
String StringLabel034 = "Majelis Persatuan Partai";
String StringLabel035 = "Dewan Pimpinan Pusat";
String StringLabel036 = "Mahkamah Partai";
String StringLabel037 = "Visi Perindo";
String StringLabel038 = "Misi Perindo";
String StringLabel039 = "Kunjungi Channel Kami";
String StringLabel040 = "YouTube";
String StringLabel041 = "MeTube";
String StringLabel042 = "Jln. Pangeran Diponegoro No.29 - Menteng\nJakarta Pusat 10310";
String StringLabel043 = "Berita Pilihan";

String StringMenu001 = "Tentang";
String StringMenu002 = "Aksi Perindo";
String StringMenu003 = "Masa Depan Milik Kita";
String StringMenu004 = "Rumah Perindo";
String StringMenu005 = "Stories";
String StringMenu006 = "Dukung";

String StringMenu007 = "Dukung\nPerindo";
String StringMenu007IconPath = "images/img_menuicon_001.png";
String StringMenu008 = "Aksi\nPerindo";
String StringMenu008IconPath = "images/img_menuicon_002.png";
String StringMenu009 = "Masa Depan\nMilik Kita";
String StringMenu009IconPath = "images/img_menuicon_003.png";
String StringMenu010 = "Aku, Kamu, Kita\nPerindo";
String StringMenu010IconPath = "images/img_menuicon_004.png";

String StringPhoto0001 = "images/img_posting_20190612_002.jpg";
String StringPhoto0002 = "images/img_posting_20190613_001.jpg";
String StringPhoto0003 = "images/img_posting_20190613_002.jpg";
String StringPhoto0004 = "images/img_posting_20190613_003.jpg";
String StringPhoto0005 = "images/img_posting_20190613_004.jpg";
String StringPhoto0006 = "images/img_user_20190613_001.jpg";
String StringPhoto0007 = "images/img_posting_20190613_005.jpg";
String StringPhoto0008 = "images/img_posting_20190614_001.jpg";
String StringPhoto0009 = "images/img_posting_20190614_002.jpg";
String StringPhoto0010 = "images/img_posting_20190614_003.jpg";
String StringPhoto0011 = "images/img_facebook_circle_512px.png";
String StringPhoto0012 = "images/img_twitter_circle_512px.png";
String StringPhoto0013 = "images/img_instagram_circle_512px.png";
String StringPhoto0014 = "https://lh3.googleusercontent.com/k2yEDmuza1AkV2_hBi25ZbLUjJCWPtZT1ELdPJlurLk8165jowzDvVpPF0f7G8kxPJo=s512-rw";
String StringPhoto0015 = "images/img_metube_white1_64px.png";
String StringPhoto0016 = "images/img_youtube_white1_64px.png";
String StringPhoto0017 = "images/img_instagram_white1_64px.png";
String StringPhoto0018 = "images/img_twitter_white1_64px.png";
String StringPhoto0019 = "images/img_facebook_white1_64px.png";
String StringPhoto0020 = "images/img_perindo_header1.png";
String StringPhoto0021 = "images/img_personfemale_grey1_512px.png";
String StringPhoto0022 = "images/img_personmale_grey1_512px.png";
String StringPhoto0023 = "images/img_posting_20190625_001.jpg";

String StringTitle = "Partai Perindo";

String memo1 = "JAKARTA – Anjuran untuk membubarkan dua kubu koalisi pendukung pasangan calon presiden-wakil presiden dalam Pilpres 2019 mengemuka. Usulan tersebut disampaikan oleh Wakil Sekjen Partai Demokrat Rachland Nashidik melalui akun twitter-nya, Minggu (9/6/2019). Menanggapi hal ini, Wakil Sekretaris Tim Kampanye Nasional (TKN) Jokowi-Ma’ruf Amin, Ahmad Rofiq turut angkat bicara. Menurutnya, pernyataan Demokrat tersebut menunjukkan ketidakmatangan partai berlambang mercy itu dalam berpolitik.";